apiVersion: v1
kind: Service
metadata:
  name: loan-calculator-service
spec:
  type: LoadBalancer
  selector:
    app: loan-calculator
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
